# Generated by Django 5.2.10 on 2026-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiDevice',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ชื่ออุปกรณ์')),
                ('carplate', models.CharField(blank=True, max_length=20, verbose_name='ทะเบียนรถ')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC Address')),
                ('mqtt_topic', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
            ],
        ),
    ]
