# Generated by Django 5.2.10 on 2026-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='Device ID')),
                ('driver_id', models.CharField(max_length=100, verbose_name='Driver ID')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('timestamp', models.DateTimeField(verbose_name='Device Timestamp')),
                ('offset_ms', models.IntegerField(verbose_name='Offset (ms)')),
                ('co2', models.FloatField(verbose_name='CO2')),
                ('ear', models.FloatField(verbose_name='EAR')),
                ('mar', models.FloatField(verbose_name='MAR')),
                ('gyro_x', models.FloatField(verbose_name='Gyroscope X')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
                'ordering': ['-timestamp', 'offset_ms'],
            },
        ),
    ]
