# Generated by Django 5.2.10 on 2026-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100, verbose_name='Driver ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Prediction Time')),
                ('co2', models.FloatField(verbose_name='CO2')),
                ('ear', models.FloatField(verbose_name='EAR')),
                ('mar', models.FloatField(verbose_name='MAR')),
                ('gyro_x', models.FloatField(verbose_name='Gyroscope X')),
                ('prediction', models.FloatField(verbose_name='Prediction Score')),
                ('risk_level', models.CharField(choices=[('active', 'Active'), ('drowsy', 'Drowsy')], max_length=10, verbose_name='Risk Level')),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-timestamp'],
            },
        ),
    ]
