# Generated by Django 5.2.10 on 2026-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_predictionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100, verbose_name='Driver ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name='Driver Name')),
                ('device_id', models.CharField(max_length=50, verbose_name='Device ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Alert Time')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
